name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version-file: "go.mod"

    - name: Download Modules
      run: go mod download

    - name: Build
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: "0"
      run: go build -ldflags="-X noutaja/command/version.GitCommit=${{ github.sha }} -X noutaja/command/version.Prerelease="""

    - name: Generate Version
      run: echo "VERSION=$(./noutaja version)" >> "${GITHUB_ENV}"

    - name: Store Noutaja Binary
      uses: actions/upload-artifact@v3
      with:
        name: noutaja
        path: noutaja

    - name: Release
      if: ${{ github.ref_name == 'main' }}
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ env.VERSION }}
        tag_name: ${{ env.VERSION }}
        files: noutaja
